name: Publish

on: [push, workflow_dispatch]

jobs:
  buildnormal:
    name: Publish binaries normal
    runs-on: ubuntu-latest
    container: 
      image: "ghcr.io/devinbayly/godot_custom:latest"
    steps:
    - uses: actions/checkout@v2
    - name: BuildScons
      run: scons platform=x11 -j$(nproc)
    - name: store artifact
      uses: actions/upload-artifact@v3
      with:
        name: godot_normal
        path: bin/godot.x11.tools.64
        retention-days: 1
  pushnormal:
    needs: buildnormal
    name: Push normal binaries
    runs-on: ubuntu-latest
    steps:
    - name: get artifact
      uses: actions/download-artifact@v3
      with:
        name: godot_normal
        path: bin/godot.x11.tools.64
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/godot.x11.tools.64
        asset_name: godot_normal
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
  buildwindows:
    name: Publish binaries for windows
    runs-on: ubuntu-latest
    container: 
      image: "ghcr.io/devinbayly/godot_custom:latest"
    steps:
    - uses: actions/checkout@v2
    - name: BuildScons
      run: scons platform=windows -j$(nproc)
    - name: show dir
      run: ls -rtlh
    - name: store artifact
      uses: actions/upload-artifact@v3
      with:
        name: godot_windows.exe
        path: bin/godot.windows.tools.64.exe
        retention-days: 1
  attemptwindowspush:
    needs: buildwindows
    runs-on: ubuntu-latest
    container: 
      image: "ghcr.io/devinbayly/godot_custom:latest"
    steps:
    - name: get artifact
      uses: actions/download-artifact@v3
      with:
        name: godot_windows.exe
        path: bin/godot.windows.tools.64.exe
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/godot.windows.tools.64.exe
        asset_name: godot_windows.exe
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
    
    
  buildllvm:
    name: build binaries llvm
    runs-on: ubuntu-latest
    container: 
      image: "ghcr.io/devinbayly/godot_custom:latest"
    steps:
    - uses: actions/checkout@v2
    - name: BuildScons
      run: scons platform=x11 use_llvm=yes use_lld=yes -j$(nproc)
    - name: show dir
      run: ls -rtlh
    - name: show bin
      run: ls bin -rtlh
    - name: store artifact
      uses: actions/upload-artifact@v3
      with:
        name: godot_llvm
        path: bin/godot.x11.tools.64.llvm
        retention-days: 1
  pushllvm:
    needs: buildllvm
    name: Push binaries
    runs-on: ubuntu-latest
    steps:
    - name: get artifact
      uses: actions/download-artifact@v3
      with:
        name: godot_llvm
        path: bin/godot.x11.tools.64.llvm
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/godot.x11.tools.64.llvm
        asset_name: godot_llvm
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
